# common interface for all hashable nodes
# having a .hash property
interface Hashable {
    hash: String!
}

type Blob implements Hashable {
    hash: String! @unique
}

type HasFilenameRel @relationshipProperties {
    name: String!
}

type Tree implements Hashable {
    hash: String! @unique
    child_blobs: [Blob!]!
        @relationship(
            type: "HAS_CHILD_BLOB"
            direction: OUT
            properties: "HasFilenameRel"
        )
    child_trees: [Tree!]!
        @relationship(
            type: "HAS_CHILD_TREE"
            direction: OUT
            properties: "HasFilenameRel"
        )
}

type Commit implements Hashable {
    hash: String! @unique
    name: String!
    date: String!
    previous: Commit @relationship(type: "HAS_PREVIOUS", direction: OUT)
    filesystem: Tree @relationship(type: "OWNS_FILESYSTEM", direction: OUT)
}

type Branch {
    name: String!
    tracks: Commit @relationship(type: "TRACKS_COMMIT", direction: OUT)
}

# custom Mutations
type Mutation {
    mergeTree(input: TreeCreateInput!): String!
}

# custom types not part of Data model
type DiffResult {
    newitems: [DiffItem]!
    delitems: [DiffItem]!
    moditems: [DiffItem]!
}

type DiffItem {
    path: String!
    old_hash: String
    new_hash: String
}

type User {
    name: String!
}

# custom Queries
type Query {
    diffCommits(
        base_commit_hash: String!
        diffee_commit_hash: String!
    ): DiffResult!
    # fetches the commit history of a branch
    fetchCommitHistory(branch_name: String!): [Commit!]!
    # get Tree hash at path
    getTreeAtPath(commit_hash: String!, path: String!): String
}
