# common interface for all hashable nodes
# having a .hash property
interface Hashable {
    hash: String!
}

type Blob implements Hashable {
    hash: String! @unique
    has_winreg: WinRegKey @relationship(type: "HAS_WINREG", direction: OUT)
    has_symbol: [Symbol!]! @relationship(type: "HAS_SYMBOL", direction: OUT, properties: "HasSymbolAddressRel")
    has_enum: [Enum!]! @relationship(type: "HAS_ENUM", direction: OUT)
    has_struct: [WinStruct!]! @relationship(type: "HAS_STRUCT", direction: OUT)
}

type HasFilenameRel @relationshipProperties {
    name: String!
}

type Tree implements Hashable {
    hash: String! @unique
    child_blobs: [Blob!]!
        @relationship(
            type: "HAS_CHILD_BLOB"
            direction: OUT
            properties: "HasFilenameRel"
        )
    child_trees: [Tree!]!
        @relationship(
            type: "HAS_CHILD_TREE"
            direction: OUT
            properties: "HasFilenameRel"
        )
}

type Commit implements Hashable {
    hash: String! @unique
    name: String!
    date: String!
    previous: Commit @relationship(type: "HAS_PREVIOUS", direction: OUT)
    filesystem: Tree @relationship(type: "OWNS_FILESYSTEM", direction: OUT)
}

type Branch {
    name: String!
    tracks: Commit @relationship(type: "TRACKS_COMMIT", direction: OUT)
}

# Plugins types
## Registry
type WinRegValue implements Hashable {
    hash: String! @unique
    type: String!
    value: String!
}

type WinRegKey implements Hashable {
    hash: String! @unique
    child_values: [WinRegValue!]!
        @relationship(
            type: "HAS_CHILD"
            direction: OUT
            properties: "HasFilenameRel"
        )
    child_keys: [WinRegKey!]!
        @relationship(
            type: "HAS_CHILD"
            direction: OUT
            properties: "HasFilenameRel"
        )
}

## PDBs
type Symbol {
    name: String!
}

type HasSymbolAddressRel @relationshipProperties {
    address: String!
}

type Enum implements Hashable {
    hash: String! @unique
    name: String!
    members: [EnumMember!]!
        @relationship(type: "HAS_MEMBER", direction: OUT)
}

type EnumMember implements Hashable {
    hash: String! @unique
    name: String!
    value: String!
}

type WinStruct implements Hashable {
    hash: String! @unique
    name: String!
    size: Int!
    kind: String!
    fields: [WinStructField!]!
        @relationship(type: "HAS_FIELD", direction: OUT)
}

type WinStructField implements Hashable {
    hash: String! @unique
    name: String!
    offset: Int!
    type: String!
}

# custom Mutations
type Mutation {
    mergeTree(input: TreeCreateInput!): String!
}

# custom types not part of Data model
type DiffResult {
    newitems: [DiffItem]!
    delitems: [DiffItem]!
    moditems: [DiffItem]!
}

type DiffItem {
    path: String!
    old_hash: String
    new_hash: String
}

type User {
    name: String!
}

# custom Queries
type Query {
    diffCommits(
        base_commit_hash: String!
        diffee_commit_hash: String!
    ): DiffResult!
    # fetches the commit history of a branch
    fetchCommitHistory(branch_name: String!): [Commit!]!
    # given a node hash, traverse the children nodes following the path
    traversePath(tree_hash: String!, path: String!): String
    # get all the possibile data labels associated with an os
    getCommitExtractedDataLabels(commit_hash: String!): [String!]!
}
