# common interface for all hashable nodes
# having a .hash property
interface Hashable {
    hash: String!
}

type Blob implements Hashable {
    hash: String! @unique
}

interface HasFilenameRel @relationshipProperties {
    name: String!
}

type Tree implements Hashable {
    hash: String! @unique
    child_blobs: [Blob] @relationship(type: "HAS_CHILD_BLOB", direction: OUT, properties: "HasFilenameRel")
    child_trees: [Tree] @relationship(type: "HAS_CHILD_TREE", direction: OUT, properties: "HasFilenameRel")
}

type Commit implements Hashable {
    hash: String! @unique
    name: String!
    date: String!
    previous: Commit @relationship(type: "HAS_PREVIOUS", direction: OUT)
    filesystem: Tree @relationship(type: "OWNS_FILESYSTEM", direction: OUT)
}

type Branch {
    name: String!
    tracks: Commit @relationship(type: "TRACKS_COMMIT", direction: OUT)
}

type Mutation {
    mergeTree(input: TreeCreateInput!): String!
}
